### ISSUE TITLE
surface pro7 i5不兼容

### ISSUE THREAD

**Issue by Bredy1992** [ati46/surfacepro7-oc#1]
反馈问题，安装进度条一半中止
亲 能否出一套详细的安装图文，吧里有很想装白需求

**Comment by wxyttty** [comment]
我记得安装bigsur好像要重启好几次的，安装记得-v不然不知道是错误导致重启还是正常重启

**Comment by ati46** [comment]
> 反馈问题，安装进度条一半中止
> 亲 能否出一套详细的安装图文，吧里有很想装白需求

请描述清楚：
1.进入到了安装界面后，选择语言和磁盘的安装过程中重启？
2.未进入到安装界面就重启？
2.1 添加-v debug=0x100 参数，查看详细的报错日志
2.2 更改i5的ig-platform-id


想要折腾surface，请详细了解一下黑苹果。
opencore请参考OC官方文档。
这个OC只针对于sruface pro 7 ，所以没有必要出具体的文档。

**Comment by GITHUBNULLING** [comment]
> > 反馈问题，安装进度条一半中止
> > 亲 能否出一套详细的安装图文，吧里有很想装白需求
> 
> 请描述清楚：
> 1.进入到了安装界面后，选择语言和磁盘的安装过程中重启？
> 2.未进入到安装界面就重启？
> 2.1 添加-v debug=0x100 参数，查看详细的报错日志
> 2.2 更改i5的ig-platform-id
> 
> 想要折腾surface，请详细了解一下黑苹果。
> opencore请参考OC官方文档。
> 这个OC只针对于sruface pro 7 ，所以没有必要出具体的文档。

你好，i5版使用此EFI，用OC引导Win10直接蓝屏，在config里添加了启动文件路径，但就是蓝屏，用自带引导就不会，引导文件都是相同的。不知如何解决，另外查到一个未排除的原因是SSDT不对：http://7.daliansky.net/11.0/SyncRuntimePermissions.jpg
不知道i7和i5的SSDT是否兼容通用呢？还望指教。
