### ISSUE TITLE
WiFi无法驱动

### ISSUE THREAD

**Issue by maimu6** [ati46/surfacepro7-oc#2]
surface pro i5 15.6 安装正常，ax201 WiFi无法驱动 ，蓝牙正常。

**Comment by ati46** [comment]
具体怎么操作的？
有没有按照git的文档来操作https://github.com/OpenIntelWireless

**Comment by 891719866** [comment]
我的是pro7 i5 8G 128G配置，安装了15.7，安装完替换了efi，也是发现蓝牙可用，wifi不可用，是还需要怎么样的配置吗，那个git好像没看到有操作介绍

**Comment by ati46** [comment]
Wi-Fi需要配套的app

**Comment by g707175425** [comment]
下载 https://github.com/zxystd/HeliPort 安装后就可以像mac源生的wifi一样连无线
