### ISSUE TITLE
whatevergreen igfx: @ CDC :failed to find symbol

### ISSUE THREAD

**Issue by wxyttty** [ati46/surfacepro7-oc#3]
我是surface pro 6，
![IMG_20200915_123529](https://user-images.githubusercontent.com/56407086/93466796-5b57bb00-f91f-11ea-8731-d8fc283609bd.jpg)

改用了你选的whatevergreen，解决了whatevergreen igfx:@ DVMT failed to find instructions of interest .Aborted pathing
但@CDC的错误还在
请问这个怎么解决
![Screenshot_2020-09-17-19-51-18-047_com miui gallery](https://user-images.githubusercontent.com/56407086/93466693-40854680-f91f-11ea-848c-67e7a729c25e.png)

**Comment by ati46** [comment]
启动参数是否添加了 -igfxcdc 。 另外pro6最好使用原本的方式解决。 因为这里修复的是10nm的CPU的问题。 
git上有pro6完美的配置

**Comment by wxyttty** [comment]
加了，原本是minstolensize补丁，没有10.11的，git只有10.14.6的完美配置，10.15.3的那个都不好不如我之前用的，没有10.11的pro6

**Comment by ati46** [comment]
去掉这个参数试试看，本身是用来修复10nm的

**Comment by wxyttty** [comment]
没有cdc了。现在卡
generation from smc report as 2
过几天再搞了

**Comment by ati46** [comment]
更新下smc试试。 你的这些错误 pro7 并没有遇到过
