### ISSUE TITLE
引导失败

### ISSUE THREAD

**Issue by Ehco1996** [ati46/surfacepro7-oc#4]
我将oc文件夹放到了

esp分区的 efi目录下

然后用 easyuifi 添加oc目录下的opencore.efi作为引导项目

并且在surface的uefi设置里将oc作为第一引导

但是开机之后引导失败了，会自动进入uefi设置界面

请问是哪里出问题了吗？感谢

**Comment by ati46** [comment]
1.不需要添加OC引导项，把OC放到EFI后 只需要在启动项里面保留内部设备即可，启动的时候会自动引导的。
2.使用OC需要特定的bootx64的， 你可以去OC的git上下载下来替换原有的文件
3.如果还不能引导的话，估计是efi目录错了， 你再检查检查目录结构

**Comment by Ehco1996** [comment]
@ati46 

我加入opencore的bootx64之后成功安装了谢谢，

另外关于readme里的触控板设置，请问是直接将代码复制到终端里设置么？

**Comment by ati46** [comment]
是的 一行 一行复制 执行
然后重启电脑

**Comment by Ehco1996** [comment]
@ati46  谢谢回复

安装完毕之后发现的确有闪屏的问题，

我外接显示器之后的确可以用了，但是只要一把显示器断开，surface本身的屏幕也不亮了，请问有啥解决办法么

**Comment by ati46** [comment]
闪屏 修改surface屏幕的分辨率不要设置为hidpi即可
拔掉外接显示器自带的黑屏？ 一直不接外接显示器呢

**Comment by Ehco1996** [comment]
> 闪屏 修改surface屏幕的分辨率不要设置为hidpi即可
> 拔掉外接显示器自带的黑屏？ 一直不接外接显示器呢

我现在吧外接的显示器线拔掉之后，开机就直接黑屏了

**Comment by ati46** [comment]
到登陆界面然后黑屏了是吧。   
按键盘 或者等几秒就会亮屏的

**Comment by Ehco1996** [comment]
> 到登陆界面然后黑屏了是吧。
> 按键盘 或者等几秒就会亮屏的

我等了块10分钟了，还是没亮，摸着输入密码之后也没亮，但是我插上外接显示器之后，已经解锁进入系统页面了，


我才可能是因为我用rdm调了一下主显示器的分辨率导致的

**Comment by ati46** [comment]
是不是显示器edid的问题？
你这个情况我知道的几个surface都没遇到过。
其他10nm的笔记本也没这个奇怪的情况。
你自己有改动过啥，可以尝试再改改

**Comment by ati46** [comment]
不需要使用rdm
装好后在显示器那里可以直接调整分辨率

**Comment by Ehco1996** [comment]
> 是不是显示器edid的问题？
> 你这个情况我知道的几个surface都没遇到过。
> 其他10nm的笔记本也没这个奇怪的情况。
> 你自己有改动过啥，可以尝试再改改

好滴 我自己再研究研究，谢谢啦，还有一个小问题，请问触摸板的设置你是在哪里找到的资料呢？ 我还想设置一下三指拖移

**Comment by ati46** [comment]
目前没有三只拖拽的命令行， 如果你执行了所有的命令行，那么在窗口或者文件夹或者文件上轻触双击。就能拖拽了
目前只实现了这种方式的拖拽

**Comment by Ehco1996** [comment]
> 目前只实现了这种方式的拖拽

明白了 谢谢，我没其他问题了
