### ISSUE TITLE
does touch screen works?

### ISSUE THREAD

**Issue by omarhaya** [ati46/surfacepro7-oc#5]
hi can u include what works and what doesn't in English please cause I want to buy a surface pro 7 to run Hackintosh on so any info will be helpful for me , and thanks in advance .

**Comment by ati46** [comment]
Driven
Video card
Wifi
Bluetooth
Keyboard
Touchboard (the touchpad is not visible in the settings but gestures, etc. are available). 

Undriven
Power management

**Comment by omarhaya** [comment]
> Driven
> Video card
> Wifi
> Bluetooth
> Keyboard
> Touchboard (the touchpad is not visible in the settings but gestures, etc. are available).
> 
> Undriven
> Power management

Thanks and touch screen, camera?

**Comment by ati46** [comment]
Not supported at present
